/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Jonas Wolfxin",
  "description": "生如逆旅, 一苇以航",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "Jonas Wolfxin VuePress"
      }
    ]
  ],
  "pages": [
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2022-06-08T04:51:55.000Z",
        "permalink": "/pages/45bc72/",
        "categories": [
          "about",
          "bar"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about/bar/",
      "relativePath": "about/bar/README.md",
      "key": "v-22053f44",
      "path": "/pages/45bc72/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-eb9c8e0c",
      "path": "/archives/",
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-b6501c4c",
      "path": "/categories/",
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-2c3b390c",
      "path": "/tags/",
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "我的首页",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0577a224",
      "path": "/",
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654655805000
    },
    {
      "title": "About Me",
      "frontmatter": {
        "title": "About Me",
        "date": "2022-06-08T02:30:21.000Z",
        "permalink": "/pages/d61090/",
        "categories": [
          "about"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-6dff3ac2",
      "path": "/pages/d61090/",
      "headers": [
        {
          "level": 2,
          "title": "第一章",
          "slug": "第一章"
        },
        {
          "level": 3,
          "title": "1.1",
          "slug": "_1-1"
        },
        {
          "level": 3,
          "title": "1.2",
          "slug": "_1-2"
        },
        {
          "level": 2,
          "title": "第二章",
          "slug": "第二章"
        },
        {
          "level": 3,
          "title": "2.1",
          "slug": "_2-1"
        },
        {
          "level": 3,
          "title": "2.2",
          "slug": "_2-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654655805000
    },
    {
      "title": "CSS a",
      "frontmatter": {
        "title": "CSS a",
        "date": "2022-06-08T04:34:36.000Z",
        "permalink": "/pages/edd17f/",
        "categories": [
          "css"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-702d8273",
      "path": "/pages/edd17f/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654655805000
    },
    {
      "title": "three",
      "frontmatter": {
        "title": "three",
        "date": "2022-06-08T04:52:05.000Z",
        "permalink": "/pages/329cd6/",
        "categories": [
          "about",
          "bar"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about/bar/three.html",
      "relativePath": "about/bar/three.md",
      "key": "v-3583ce5a",
      "path": "/pages/329cd6/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "c-bbb",
      "frontmatter": {
        "title": "c-bbb",
        "permalink": null,
        "categories": [
          "css"
        ]
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-9da816c0",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "c-ccc",
      "frontmatter": {
        "title": "c-ccc",
        "permalink": null,
        "categories": [
          "css"
        ]
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-118d6300",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "four",
      "frontmatter": {
        "title": "four",
        "date": "2022-06-08T04:52:26.000Z",
        "permalink": "/pages/6feec4/",
        "categories": [
          "about",
          "bar"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about/bar/four.html",
      "relativePath": "about/bar/four.md",
      "key": "v-3311b6b7",
      "path": "/pages/6feec4/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "README",
      "frontmatter": {
        "title": "README",
        "date": "2022-06-08T04:50:38.000Z",
        "permalink": "/pages/45964a/",
        "categories": [
          "foo"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/foo/",
      "relativePath": "foo/README.md",
      "key": "v-1614f226",
      "path": "/pages/45964a/",
      "headers": [
        {
          "level": 2,
          "title": "fadfa",
          "slug": "fadfa"
        },
        {
          "level": 3,
          "title": "fdafaf",
          "slug": "fdafaf"
        },
        {
          "level": 2,
          "title": "fieldset",
          "slug": "fieldset"
        },
        {
          "level": 3,
          "title": "fdasfdfcdf",
          "slug": "fdasfdfcdf"
        },
        {
          "level": 2,
          "title": "fdsaf",
          "slug": "fdsaf"
        },
        {
          "level": 3,
          "title": "fdsfds",
          "slug": "fdsfds"
        }
      ]
    },
    {
      "title": "Contact",
      "frontmatter": {
        "title": "Contact",
        "categories": [
          "foo"
        ],
        "navbar": true
      },
      "regularPath": "/foo/contact.html",
      "relativePath": "foo/contact.md",
      "key": "v-fc299000",
      "path": "/foo/contact.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ]
    },
    {
      "title": "c-aaa",
      "frontmatter": {
        "title": "c-aaa",
        "permalink": null,
        "categories": [
          "css"
        ]
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-50ca8640",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    },
    {
      "title": "About Me1",
      "frontmatter": {
        "title": "About Me1",
        "navbar": true,
        "date": "2022-06-08T03:53:23.000Z",
        "permalink": "/pages/4b4c39/",
        "categories": [
          "about1"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/about1/",
      "relativePath": "about1/README.md",
      "key": "v-fd99fc5e",
      "path": "/pages/4b4c39/",
      "headers": [
        {
          "level": 2,
          "title": "第一章",
          "slug": "第一章"
        },
        {
          "level": 3,
          "title": "1.1",
          "slug": "_1-1"
        },
        {
          "level": 3,
          "title": "1.2",
          "slug": "_1-2"
        },
        {
          "level": 2,
          "title": "第二章",
          "slug": "第二章"
        },
        {
          "level": 3,
          "title": "2.1",
          "slug": "_2-1"
        },
        {
          "level": 3,
          "title": "2.2",
          "slug": "_2-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654655805000
    },
    {
      "title": "one",
      "frontmatter": {
        "title": "one",
        "date": "2022-06-08T04:51:05.000Z",
        "permalink": "/pages/780068/",
        "categories": [
          "foo"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/foo/one.html",
      "relativePath": "foo/one.md",
      "key": "v-27378580",
      "path": "/pages/780068/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    },
    {
      "title": "two",
      "frontmatter": {
        "title": "two",
        "date": "2022-06-08T04:51:28.000Z",
        "permalink": "/pages/0f8bb5/",
        "categories": [
          "foo"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/foo/two.html",
      "relativePath": "foo/two.md",
      "key": "v-15eb9e00",
      "path": "/pages/0f8bb5/",
      "headers": [
        {
          "level": 2,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题"
        },
        {
          "level": 2,
          "title": "3 二级标题",
          "slug": "_3-二级标题"
        },
        {
          "level": 3,
          "title": "三级标题",
          "slug": "三级标题-2"
        }
      ],
      "lastUpdated": "6/8/2022, 11:59:29 AM",
      "lastUpdatedTimestamp": 1654682369000,
      "createdTime": 1654682369000
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about/"
      },
      {
        "text": "About1",
        "link": "/about1/"
      },
      {
        "text": "FOO",
        "link": "/foo/"
      },
      {
        "text": "美丽的CSS",
        "link": "/css/"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "About",
                "link": "/about/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "About",
                "link": "/about/"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}